#!/usr/bin/env python3 
#
# ./mkparams <param-n>
#
# DESCRIPTION: Print a parameter file for n=<> to stdtout
#
# Author: niklasdewally
# Date: 2025/06/13

import random
import sys

n = int(sys.argv[1])
number_of_clusters = 3

import random
random.seed(42)

coords = [(random.randint(0, 100), random.randint(0, 100)) for i in range(n)]

x = [coord[0] for coord in coords]
y = [coord[1] for coord in coords]

x_str = ",".join([str(i) for i in x])
y_str = ",".join([str(i) for i in y])

print(f"letting n be {n}")
print(f"letting number_of_clusters be {number_of_clusters}")
print(f"letting x be [{x_str}]")
print(f"letting y be [{y_str}]")
